brand_model_frequency = {
    "Mahindra XUV500 W8 2WD": 49,
    "Maruti Swift VDI": 45,
    "Honda City 1.5 S MT": 34,
    "Maruti Swift Dzire VDI": 34,
    "Maruti Swift VDI BSIV": 31,
    "Maruti Ritz VDi": 30,
    "Hyundai i10 Sportz": 30,
    "Toyota Fortuner 3.0 Diesel": 29,
    "Honda Amaze S i-Dtech": 27,
    "Hyundai Grand i10 Sportz": 27,
    "Maruti Ertiga VDI": 25,
    "Honda Brio S MT": 25,
    "Honda City 1.5 V MT": 24,
    "Hyundai Verna 1.6 SX": 23,
    "Maruti Wagon R VXI": 23,
    "Maruti Wagon R LXI": 22,
    "Maruti Alto LXi": 21,
    "Hyundai EON Era Plus": 20,
    "Maruti Ertiga ZDI": 20,
    "Skoda Superb Elegance 1.8 TSI AT": 20,
    "BMW 3 Series 320d": 20,
    "Maruti Alto 800 LXI": 20,
    "Toyota Fortuner 4x2 AT": 19,
    "Hyundai i10 Magna 1.2": 19,
    "Maruti Celerio VXI AT": 19,
    "Renault KWID RXT": 18,
    "Volkswagen Vento Diesel Highline": 18,
    "Maruti Wagon R LXI CNG": 18,
    "Hyundai i20 1.2 Magna": 18,
    "Maruti Swift Dzire VXI": 18,
    "Volkswagen Polo 1.2 MPI Highline": 18,
    "Volkswagen Polo 1.5 TDI Highline": 18,
    "Ford Figo Diesel EXI": 17,
    "Audi A4 2.0 TDI": 17,
    "Ford Figo Diesel Titanium": 17,
    "Renault Duster 110PS Diesel RxZ": 17,
    "Volkswagen Polo Diesel Comfortline 1.2L": 17,
    "Hyundai i10 Sportz 1.2": 16,
    "Ford Figo Diesel ZXI": 16,
    "Maruti Alto K10 VXI": 16,
    "Hyundai Creta 1.6 CRDi SX": 16,
    "Toyota Fortuner 4x2 Manual": 16,
    "Ford Ecosport 1.5 DV5 MT Titanium Optional": 16,
    "Volkswagen Polo Petrol Comfortline 1.2L": 16,
    "Honda Amaze S i-Vtech": 16,
    "Maruti Swift Dzire VDi": 16,
    "Hyundai Grand i10 AT Asta": 16,
    "Mahindra XUV500 W6 2WD": 15,
    "Ford Ecosport 1.5 DV5 MT Titanium": 15,
    "Hyundai i20 Sportz 1.2": 15,
    "Audi A4 2.0 TDI 177 Bhp Premium Plus": 15,
    "Hyundai Verna 1.6 SX VTVT": 15,
    "Honda City i VTEC SV": 15,
    "Hyundai i10 Magna": 15,
    "Toyota Innova Crysta 2.8 ZX AT": 14,
    "BMW 3 Series 320d Luxury Line": 14,
    "Maruti Wagon R LXI BS IV": 14,
    "Renault Duster 85PS Diesel RxL": 14,
    "Toyota Innova 2.5 V Diesel 7-seater": 14,
    "Jaguar XF 2.2 Litre Luxury": 14,
    "Maruti Swift ZDi": 13,
    "Mahindra XUV500 W10 2WD": 13,
    "Honda City i VTEC CVT VX": 13,
    "Hyundai i20 Sportz 1.4 CRDi": 13,
    "Hyundai Grand i10 CRDi Sportz": 13,
    "Honda City i VTEC V": 13,
    "Hyundai Santro Xing GLS": 13,
    "Mahindra XUV500 W8 4WD": 13,
    "Hyundai i10 Era": 13,
    "Audi A6 2011-2015 2.0 TDI Premium Plus": 13,
    "Volkswagen Vento 1.5 TDI Highline": 12,
    "Hyundai i20 1.2 Sportz": 12,
    "Maruti Swift VXI BSIV": 12,
    "BMW X1 sDrive20d": 12,
    "Hyundai Creta 1.6 CRDi SX Option": 12,
    "Hyundai i20 Asta 1.4 CRDi": 12,
    "Maruti Swift Dzire LDI": 12,
    "Hyundai EON D Lite Plus": 12,
    "Volkswagen Polo Petrol Highline 1.2L": 12,
    "BMW 5 Series 520d Luxury Line": 12,
    "Hyundai Verna 1.6 SX CRDi (O)": 12,
    "Volkswagen Vento Petrol Highline": 12,
    "Honda Amaze VX i-DTEC": 12,
    "Audi Q7 3.0 TDI Quattro Premium Plus": 12,
    "Hyundai Grand i10 CRDi Magna": 12,
    "Chevrolet Beat LT": 12,
    "Maruti Vitara Brezza ZDi Plus Dual Tone": 12,
    "Toyota Innova 2.5 G (Diesel) 8 Seater": 12,
    "Maruti Alto K10 2010-2014 VXI": 12,
    "Volkswagen Polo Diesel Trendline 1.2L": 11,
    "Mercedes-Benz New C-Class C 220d Avantgarde Edition C": 11,
    "Maruti Alto LXi BSIII": 11,
    "Honda City i DTEC VX": 11,
    "Maruti Swift Dzire VXi": 11,
    "Hyundai Grand i10 1.2 Kappa Sportz": 11,
    "Ford Figo Petrol ZXI": 11,
    "Hyundai Verna 1.6 SX VTVT (O)": 11,
    "Maruti Alto 800 2016-2019 LXI": 11,
    "Hyundai Grand i10 Asta": 11,
    "Chevrolet Beat LS": 11,
    "Maruti Wagon R VXI BS IV": 11,
    "Hyundai i20 Asta Option 1.2": 11,
    "Volkswagen Polo Diesel Highline 1.2L": 11,
    "Hyundai Accent GLE": 10,
    "Hyundai Creta 1.6 SX Plus Dual Tone Petrol": 10,
    "Ford Endeavour 3.2 Titanium AT 4X4": 10,
    "Mahindra Ssangyong Rexton RX7": 10,
    "BMW 5 Series 2013-2017 520d Luxury Line": 10,
    "Hyundai Creta 1.6 SX Plus Petrol Automatic": 10,
    "Maruti Eeco 7 Seater Standard": 10,
    "Audi A4 2.0 TDI Multitronic": 10,
    "Renault Duster 110PS Diesel RxL": 10,
    "Mercedes-Benz New C-Class C 220 CDI Avantgarde": 10,
    "Hyundai Creta 1.6 CRDi AT SX Plus": 10,
    "Honda City V MT": 10,
    "Maruti Celerio VXI": 10,
    "BMW 3 Series Luxury Line": 10,
    "Hyundai i20 1.2 Spotz": 10,
    "Hyundai i20 Magna": 10,
    "Hyundai i20 Asta 1.2": 10,
    "Maruti A-Star Vxi": 10,
    "Maruti Swift Dzire Tour LDI": 10,
    "Chevrolet Beat Diesel LT": 10,
    "Mercedes-Benz New C-Class C 220 CDI Elegance AT": 10,
    "Hyundai Xcent 1.1 CRDi Base": 10,
    "Honda City i DTEC SV": 10,
    "Toyota Innova 2.5 VX (Diesel) 7 Seater": 10,
    "BMW 3 Series 320d Highline": 10,
    "Chevrolet Cruze LTZ": 10,
    "Ford EcoSport 1.5 TDCi Titanium": 9,
    "Hyundai Elantra CRDi SX": 9,
    "Hyundai i10 Magna 1.1": 9,
    "Hyundai Grand i10 1.2 Kappa Asta": 9,
    "Maruti Swift VXI": 9,
    "Toyota Etios Liva GD": 9,
    "Volkswagen Polo 1.2 MPI Comfortline": 9,
    "Toyota Innova 2.5 G4 Diesel 8-seater": 9,
    "Toyota Etios G": 9,
    "Honda Brio VX AT": 9,
    "Volkswagen Vento Petrol Highline AT": 9,
    "Honda City 1.5 V AT": 9,
    "Hyundai i10 Era 1.1": 9,
    "Honda City ZX GXi": 9,
    "Hyundai i10 Sportz AT": 9,
    "Mercedes-Benz New C-Class 220 CDI AT": 9,
    "Maruti Baleno Zeta 1.2": 8,
    "Mercedes-Benz M-Class ML 350 4Matic": 8,
    "Maruti Ciaz ZDi Plus SHVS": 8,
    "Maruti Swift ZXI": 8,
    "Mercedes-Benz GLE 350d": 8,
    "Maruti Swift Dzire ZXi": 8,
    "Maruti Vitara Brezza ZDi Plus": 8,
    "Honda Civic 2006-2010 1.8 S MT": 8,
    "Hyundai Grand i10 Magna": 8,
    "Volkswagen Jetta 2013-2015 2.0L TDI Highline AT": 8,
    "Toyota Etios GD": 8,
    "Land Rover Freelander 2 SE": 8,
    "Hyundai Xcent 1.1 CRDi S": 8,
    "Chevrolet Cruze LTZ AT": 8,
    "Toyota Innova 2.5 V Diesel 8-seater": 8,
    "Ford Ikon 1.3 Flair": 8,
    "Toyota Innova 2.5 GX (Diesel) 7 Seater": 8,
    "Mercedes-Benz E-Class 2009-2013 E250 CDI Elegance": 8,
    "BMW X5 xDrive 30d": 8,
    "Volkswagen Polo GT TSI": 8,
    "Mercedes-Benz GLA Class 200 CDI SPORT": 8,
    "Volkswagen Polo Petrol Trendline 1.2L": 8,
    "Hyundai Grand i10 1.2 Kappa Magna": 8,
    "Maruti Ritz VXi": 8,
    "Volkswagen Vento Diesel Comfortline": 8,
    "Mercedes-Benz E-Class 280 CDI": 8,
    "Hyundai EON Magna Plus": 8,
    "Maruti Vitara Brezza ZDi": 8,
    "Maruti Alto K10 VXI AGS": 8,
    "Maruti Omni 8 Seater BSIV": 7,
    "BMW 5 Series 2003-2012 520d": 7,
    "BMW 5 Series 2013-2017 530d M Sport": 7,
    "Maruti Wagon R LXI BSIII": 7,
    "Maruti SX4 ZXI MT BSIV": 7,
    "Honda City i VTEC VX Option": 7,
    "Maruti Ritz LDi": 7,
    "Mercedes-Benz GL-Class 2007 2012 350 CDI Luxury": 7,
    "Skoda Superb Style 1.8 TSI AT": 7,
    "Mahindra Bolero ZLX": 7,
    "Hyundai i20 1.2 Asta Option": 7,
    "Toyota Fortuner 4x4 MT": 7,
    "Maruti Ertiga VXI": 7,
    "Volkswagen Vento 1.5 TDI Highline AT": 7,
    "Toyota Innova 2.5 G (Diesel) 7 Seater BS IV": 7,
    "Toyota Corolla Altis 2008-2013 1.8 VL AT": 7,
    "Tata Nano Twist XT": 7,
    "Mahindra XUV500 AT W10 FWD": 7,
    "Maruti Ciaz VXi Plus": 7,
    "Hyundai Elite i20 Petrol Asta": 7,
    "Hyundai Santro Xing XL eRLX Euro III": 7,
    "Toyota Innova 2.5 G (Diesel) 8 Seater BS IV": 7,
    "Nissan Sunny 2011-2014 Diesel XL": 7,
    "Honda Civic 2006-2010 1.8 V MT": 7,
    "Nissan Micra Diesel XV": 7,
    "Honda Jazz 1.2 SV i VTEC": 7,
    "Maruti Ciaz VDi Plus SHVS": 7,
    "Hyundai Verna 1.6 SX CRDI (O) AT": 7,
    "Jaguar XF 3.0 Litre S Premium Luxury": 7,
    "Audi A4 New 2.0 TDI Multitronic": 7,
    "Maruti Dzire VDI": 7,
    "Hyundai i20 1.4 CRDi Magna": 7,
    "Mahindra Scorpio SLE BSIV": 7,
    "Hyundai Verna SX CRDi AT": 7,
    "Maruti Baleno Zeta Automatic": 7,
    "Toyota Innova Crysta 2.4 VX MT": 7,
    "Mercedes-Benz E-Class 2015-2017 E250 CDI Avantgarde": 7,
    "Maruti Alto 800 VXI": 7,
    "Hyundai Verna 1.6 VTVT": 7,
    "Honda City i DTEC V": 7,
    "Mercedes-Benz B Class B180": 7,
    "Honda Brio V MT": 7,
    "Mercedes-Benz CLA 200 CDI Sport": 7,
    "Hyundai Santro Xing GL": 7,
    "Honda City i-VTEC CVT VX": 7,
    "BMW 3 Series 320d Sport Line": 7,
    "Mercedes-Benz E-Class E250 CDI Avantgrade": 7,
    "Hyundai Grand i10 Asta Option": 7,
    "Hyundai i20 Magna 1.4 CRDi": 7,
    "Honda Jazz 1.2 V CVT i VTEC": 7,
    "Skoda Octavia Elegance 2.0 TDI AT": 7,
    "Audi A4 35 TDI Premium": 6,
    "Volkswagen Vento Diesel Trendline": 6,
    "Hyundai Verna CRDi SX": 6,
    "Maruti Alto K10 LXI": 6,
    "Toyota Fortuner 4x2 4 Speed AT": 6,
    "Mercedes-Benz M-Class ML 250 CDI": 6,
    "Toyota Fortuner 2.8 2WD AT": 6,
    "Honda City i VTEC VX": 6,
    "Hyundai i20 Magna Optional 1.2": 6,
    "Hyundai i10 Magna AT": 6,
    "Hyundai Creta 1.6 SX Plus Diesel": 6,
    "Audi Q7 4.2 TDI Quattro Technology": 6,
    "Renault KWID RXT Optional": 6,
    "Volkswagen Vento 1.6 Highline": 6,
    "Audi Q5 2.0 TDI Premium Plus": 6,
    "Audi A6 2.7 TDI": 6,
    "Chevrolet Beat Diesel LS": 6,
    "Maruti Alto 800 2016-2019 VXI": 6,
    "Hyundai Xcent 1.2 Kappa S Option": 6,
    "Hyundai EON Era": 6,
    "Maruti Swift VXi BSIV": 6,
    "Toyota Corolla Altis G": 6,
    "Hyundai Xcent 1.2 Kappa S": 6,
    "Ford Ecosport 1.5 Ti VCT MT Titanium": 6,
    "Honda Amaze SX i-VTEC": 6,
    "Toyota Innova Crysta 2.8 GX AT": 6,
    "Hyundai i20 1.2 Magna Executive": 6,
    "Tata Nano XTA": 6,
    "Toyota Innova Crysta 2.4 ZX MT": 6,
    "Mahindra Scorpio VLX": 6,
    "Tata Indica V2 eLS": 6,
    "Maruti Ertiga SHVS VDI": 6,
    "Maruti Swift 1.3 VXi": 6,
    "Nissan Micra XV CVT": 6,
    "Honda Jazz 1.2 VX i VTEC": 6,
    "Maruti Swift LDI": 6,
    "Hyundai Creta 1.6 VTVT S": 6,
    "Maruti Swift Dzire ZDI": 6,
    "Maruti Wagon R AMT VXI": 6,
    "Hyundai Santro Xing GL Plus": 5,
    "Mercedes-Benz E-Class 2009-2013 E250 CDI Blue Efficiency": 5,
    "Audi Q3 35 TDI Quattro Premium Plus": 5,
    "Maruti Swift VXI Optional": 5,
    "Nissan Sunny 2011-2014 Diesel XV": 5,
    "Honda City i-VTEC V": 5,
    "Audi Q5 30 TDI quattro Premium Plus": 5,
    "Audi A6 3.0 TDI quattro": 5,
    "Toyota Camry Hybrid": 5,
    "Audi A6 2011-2015 2.0 TDI": 5,
    "Maruti SX4 S Cross DDiS 320 Zeta": 5,
    "Maruti Swift Dzire Vdi BSIV": 5,
    "Toyota Innova 2.5 G (Diesel) 7 Seater": 5,
    "Maruti Eeco 5 STR With AC Plus HTR CNG": 5,
    "Skoda Superb Elegance 2.0 TDI CR AT": 5,
    "Toyota Etios Liva G": 5,
    "Hyundai i20 1.2 Asta": 5,
    "Audi Q7 3.0 TDI Quattro Technology": 5,
    "Toyota Fortuner 2.8 4WD MT": 5,
    "Hyundai Verna CRDi": 5,
    "Hyundai Santro Xing XO eRLX Euro II": 5,
    "Jaguar XF Diesel": 5,
    "Renault Duster 110PS Diesel RxZ AMT": 5,
    "Hyundai Santro Xing XL": 5,
    "Hyundai Santro Xing XO": 5,
    "Maruti Swift VXI BSIII": 5,
    "Volkswagen Ameo 1.2 MPI Comfortline": 5,
    "Hyundai i20 Magna 1.2": 5,
    "Mercedes-Benz New C-Class C 220 CDI Style": 5,
    "Hyundai Santro Xing XP": 5,
    "Mercedes-Benz New C-Class C 220 CDI BE Avantgare": 5,
    "BMW X1 sDrive 20d Exclusive": 5,
    "Renault Duster 85PS Diesel RxL Optional": 5,
    "BMW X5 2014-2019 xDrive 30d Design Pure Experience 7 Seater": 5,
    "Mitsubishi Pajero Sport 4X4": 5,
    "Maruti Ertiga ZXI": 5,
    "BMW 3 Series 320d Prestige": 5,
    "Hyundai EON Sportz": 5,
    "Audi A6 2011-2015 35 TDI Technology": 5,
    "Hyundai Creta 1.6 SX": 5,
    "Mini Cooper 5 DOOR D": 5,
    "Mini Cooper Convertible S": 5,
    "Maruti Swift Ldi BSIII": 5,
    "Honda City ZX CVT": 5,
    "Maruti Swift Vdi BSIII": 5,
    "Maruti Wagon R LX BSIII": 5,
    "Toyota Fortuner 4x4 AT": 5,
    "Maruti SX4 Vxi BSIV": 5,
    "Maruti Ciaz ZXi": 5,
    "Honda City 1.5 GXI": 5,
    "Hyundai i20 Asta": 5,
    "Maruti Ritz LXi": 5,
    "Ford Endeavour 3.2 Trend AT 4X4": 5,
    "Audi Q5 2008-2012 2.0 TDI": 5,
    "Nissan Micra Diesel XV Premium": 5,
    "Hyundai i10 Sportz 1.2 AT": 5,
    "Chevrolet Spark 1.0 LT": 5,
    "Renault Duster 85PS Diesel RxL Option": 5,
    "Mercedes-Benz A Class A180 CDI": 5,
    "Mercedes-Benz E-Class 2009-2013 E 220 CDI Avantgarde": 5,
    "Porsche Panamera Diesel": 5,
    "Honda City V AT": 5,
    "Honda City 1.5 S AT": 5,
    "Honda City 1.5 V MT Exclusive": 5,
    "Maruti Swift VDI BSIV W ABS": 5,
    "Maruti Celerio ZXI": 5,
    "Honda Civic 2006-2010 1.8 V AT": 5,
    "Mahindra XUV500 W10 AWD": 5,
    "Maruti Baleno Alpha 1.3": 5,
    "Ford Fiesta Classic 1.4 Duratorq CLXI": 5,
    "Volkswagen Passat Diesel Highline 2.0 TDI": 5,
    "Hyundai i20 1.4 CRDi Sportz": 5,
    "Audi Q7 35 TDI Quattro Technology": 5,
    "Chevrolet Spark 1.0 LS": 5,
    "BMW 5 Series 520d Sedan": 5,
    "BMW X5 3.0d": 5,
    "Ford Ecosport 1.5 DV5 MT Trend": 5,
    "Hyundai Verna CRDi 1.6 SX Option": 5,
    "Toyota Corolla H4": 5,
    "Maruti Wagon R VXI AMT": 5,
    "Maruti Wagon R LXI Minor": 5,
    "Honda Amaze E i-Vtech": 5,
    "Hyundai Santa Fe 4WD AT": 5,
    "Maruti Vitara Brezza VDi Option": 5,
    "Honda Brio S Option MT": 5,
    "Chevrolet Aveo U-VA 1.2 LS": 5,
    "Maruti Wagon R CNG LXI": 5,
    "Honda Amaze SX i-DTEC": 5,
    "Maruti Swift Lxi BSIII": 5,
    "Mercedes-Benz E-Class 2015-2017 E250 Edition E": 5,
    "Honda City 1.5 EXI": 5,
    "Ford Endeavour 3.0L 4X4 AT": 5,
    "Hyundai i20 Magna Optional 1.4 CRDi": 5,
    "Maruti Ciaz ZDi Plus": 5,
    "Honda Accord 2.4 AT": 5,
    "Tata Indica Vista Quadrajet VX": 5,
    "Maruti Alto 800 2016-2019 CNG LXI": 4,
    "Honda Jazz V": 4,
    "Hyundai i20 Magna 1.4 CRDi (Diesel)": 4,
    "Land Rover Range Rover 2.2L Pure": 4,
    "Hyundai i10 Sportz 1.1L": 4,
    "Ford Figo Petrol Titanium": 4,
    "Maruti Baleno Alpha": 4,
    "Audi A6 35 TDI Matrix": 4,
    "Skoda Laura Ambiente": 4,
    "Skoda Rapid 1.5 TDI AT Elegance": 4,
    "Land Rover Freelander 2 TD4 SE": 4,
    "Hyundai Creta 1.6 SX Option": 4,
    "Maruti Wagon R VXI 1.2": 4,
    "BMW 5 Series 2003-2012 525d": 4,
    "BMW X1 sDrive 20d Sportline": 4,
    "Honda City ZX VTEC": 4,
    "Honda Amaze S AT i-Vtech": 4,
    "Renault Duster 85PS Diesel RxE": 4,
    "Hyundai Verna 1.6 CRDi SX": 4,
    "Hyundai Grand i10 Asta Option AT": 4,
    "Maruti Ciaz AT ZXi": 4,
    "Hyundai Grand i10 1.2 CRDi Sportz": 4,
    "Honda Accord 2.4 MT": 4,
    "Volkswagen Polo Petrol Highline 1.6L": 4,
    "Hyundai Creta 1.6 SX Option Diesel": 4,
    "Jeep Compass 2.0 Longitude": 4,
    "Hyundai i20 Sportz Option": 4,
    "Nissan Sunny 2011-2014 XL": 4,
    "Hyundai Verna 1.6 CRDI": 4,
    "Ford EcoSport 1.5 Diesel Titanium": 4,
    "Renault Duster Petrol RxL": 4,
    "Hyundai Elantra CRDi SX AT": 4,
    "Nissan Terrano XV Premium 110 PS": 4,
    "Ford EcoSport 1.5 Ti VCT AT Titanium": 4,
    "Honda Jazz 1.5 VX i DTEC": 4,
    "Maruti A-Star Lxi": 4,
    "Hyundai Verna 1.6 SX VTVT (O) AT": 4,
    "Tata Indigo CS eVX": 4,
    "Maruti Swift Dzire VDI Optional": 4,
    "Mercedes-Benz GL-Class 350 CDI Blue Efficiency": 4,
    "Honda CR-V 2.4 AT": 4,
    "Renault Duster 110PS Diesel RxZ Plus": 4,
    "Hyundai i20 Sportz Option 1.2": 4,
    "Volkswagen CrossPolo 1.5 TDI": 4,
    "Mercedes-Benz New C-Class C250 Avantgarde": 4,
    "Nissan Terrano XL": 4,
    "Toyota Corolla Altis Diesel D4DG": 4,
    "Fiat Avventura MULTIJET Emotion": 4,
    "Toyota Corolla Altis VL": 4,
    "Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV": 4,
    "Hyundai i20 1.4 Sportz": 4,
    "Maruti Swift Dzire 1.2 Vxi BSIV": 4,
    "Toyota Corolla Altis 1.8 VL CVT": 4,
    "Audi Q3 2012-2015 2.0 TDI Quattro Premium Plus": 4,
    "Maruti Baleno Delta 1.2": 4,
    "Tata Zest Revotron 1.2T XM": 4,
    "Tata Indica Vista Quadrajet LS": 4,
    "Maruti Celerio VXI AMT": 4,
    "Toyota Innova 2.5 GX (Diesel) 8 Seater": 4,
    "Maruti Swift Dzire ZXI": 4,
    "Maruti Ertiga VXI CNG": 4,
    "Honda Mobilio S i DTEC": 4,
    "Toyota Corolla 1.8 J": 4,
    "Ford Ecosport 1.5 DV5 MT Ambiente": 4,
    "Volkswagen Ameo 1.2 MPI Highline": 4,
    "Maruti Dzire AMT ZDI Plus": 4,
    "Tata Zest Revotron 1.2T XE": 4,
    "Hyundai Xcent 1.2 CRDi S": 4,
    "BMW X3 xDrive20d": 4,
    "Hyundai Santro GLS II - Euro II": 4,
    "Mahindra TUV 300 2015-2019 T8": 4,
    "Datsun redi-GO T Option": 4,
    "Maruti Ritz VXI": 4,
    "Mercedes-Benz B Class B200 CDI": 4,
    "Audi Q3 2.0 TDI": 4,
    "Hyundai i20 1.2 Sportz Option": 4,
    "Hyundai Elantra 2.0 SX Option AT": 4,
    "Mercedes-Benz GLE 250d": 4,
    "Hyundai i20 Sportz AT 1.4": 4,
    "Volkswagen Vento 1.6 Comfortline": 4,
    "BMW 3 Series 320d Sedan": 4,
    "Hyundai i10 Asta": 4,
    "Tata Indigo LS": 4,
    "Hyundai Santa Fe 4X4": 4,
    "Tata Zest Quadrajet 1.3 75PS XE": 4,
    "Renault KWID RXL": 4,
    "Skoda Rapid 1.6 TDI Ambition": 4,
    "Audi Q3 35 TDI Quattro Premium": 4,
    "Honda City 1.5 E MT": 4,
    "Toyota Innova 2.5 G4 Diesel 7-seater": 4,
    "Volkswagen Vento 2013-2015 1.6 Comfortline": 4,
    "Honda Mobilio S i VTEC": 4,
    "Skoda Laura Ambiente 2.0 TDI CR AT": 4,
    "Honda City i-VTEC VX": 4,
    "Mercedes-Benz New C-Class C 200 CGI Avantgarde": 4,
    "Hyundai i20 1.4 CRDi Asta": 4,
    "Mercedes-Benz S Class 2005 2013 S 350 CDI": 4,
    "BMW 3 Series 320i Sedan": 4,
    "Honda Amaze VX i-Vtech": 4,
    "Mercedes-Benz GLA Class 200 CDI": 4,
    "Mercedes-Benz E-Class E 220 d": 4,
    "Land Rover Range Rover HSE Dynamic": 4,
    "Hyundai Santa Fe 4x4 AT": 4,
    "Honda WRV i-VTEC VX": 4,
    "Maruti Swift Dzire LXI": 4,
    "BMW X1 sDrive 20d xLine": 4,
    "Honda BRV i-VTEC V CVT": 4,
    "Hyundai Verna 1.6 SX VTVT AT": 3,
    "Volvo XC60 D5": 3,
    "Audi Q5 3.0 TDI Quattro Technology": 3,
    "Hyundai i20 Sportz Diesel": 3,
    "Mercedes-Benz E-Class 2009-2013 E350 Petrol": 3,
    "Honda Civic 2010-2013 1.8 V MT": 3,
    "Maruti Estilo LXI": 3,
    "Maruti Celerio ZDi": 3,
    "Renault Scala Diesel RxL": 3,
    "Maruti Swift Dzire ZDi": 3,
    "Maruti SX4 Vxi BSIII": 3,
    "Mercedes-Benz New C-Class C 200 Kompressor Elegance AT": 3,
    "Maruti Swift Dzire AMT ZDI": 3,
    "Honda Jazz S": 3,
    "Audi Q7 45 TDI Quattro Technology": 3,
    "Skoda Rapid 1.5 TDI Elegance": 3,
    "Maruti Swift Ldi BSIV": 3,
    "Maruti Omni E MPI STD BS IV": 3,
    "Toyota Etios Liva 1.2 G": 3,
    "Toyota Corolla H2": 3,
    "Maruti SX4 S Cross DDiS 200 Zeta": 3,
    "Tata Manza Aura Quadrajet BS IV": 3,
    "Honda Jazz VX Diesel": 3,
    "Toyota Corolla Altis 1.8 GL": 3,
    "Volkswagen Ameo 1.5 TDI Highline": 3,
    "Mahindra Xylo H4": 3,
    "Maruti Zen LXi - BS III": 3,
    "Renault KWID 1.0 RXT Optional": 3,
    "Audi Q5 2.0 TDI": 3,
    "Maruti Dzire VXI": 3,
    "Honda Brio 1.2 VX MT": 3,
    "BMW X6 xDrive30d": 3,
    "Honda Civic 2006-2010 1.8 S AT": 3,
    "BMW X1 xDrive 20d xLine": 3,
    "Mitsubishi Pajero 2.8 SFX": 3,
    "Renault Duster 110PS Diesel RxZ Pack": 3,
    "Hyundai EON Magna": 3,
    "Honda Accord 2.4 A/T": 3,
    "Volkswagen Vento 1.5 TDI Comfortline": 3,
    "Maruti Baleno Delta 1.3": 3,
    "Chevrolet Beat Diesel": 3,
    "BMW 7 Series 730Ld Sedan": 3,
    "Honda Brio E MT": 3,
    "Hyundai Getz GLE": 3,
    "Hyundai i20 1.4 Asta": 3,
    "Ford Fiesta EXi 1.4 TDCi Ltd": 3,
    "Hyundai Verna VTVT 1.6 SX": 3,
    "Jeep Compass 2.0 Limited 4X4": 3,
    "Renault Pulse RxL": 3,
    "Maruti Baleno Alpha Diesel": 3,
    "Maruti Ciaz ZDi SHVS": 3,
    "Maruti Ciaz ZXi Plus": 3,
    "Skoda Rapid 1.6 TDI Elegance": 3,
    "Hyundai Verna Transform VTVT": 3,
    "Honda CR-V 2.0L 2WD MT": 3,
    "Honda City i-VTEC S": 3,
    "Toyota Innova 2.5 VX (Diesel) 8 Seater": 3,
    "Toyota Corolla Altis 1.4 DG": 3,
    "Mahindra XUV500 W4": 3,
    "Audi Q3 2.0 TDI Quattro": 3,
    "Mahindra Xylo D4": 3,
    "Maruti Celerio ZXI AT": 3,
    "Maruti Baleno RS 1.0 Petrol": 3,
    "Maruti Baleno Sigma 1.2": 3,
    "Honda City V MT Exclusive": 3,
    "Hyundai i10 Era 1.1 iTech SE": 3,
    "Toyota Fortuner 2.8 2WD MT": 3,
    "Hyundai Grand i10 1.2 Kappa Magna AT": 3,
    "Volkswagen Polo 1.5 TDI Trendline": 3,
    "Toyota Innova 2.5 ZX Diesel 7 Seater": 3,
    "Nissan Terrano XV 110 PS": 3,
    "Maruti Alto LXi BSII": 3,
    "Hyundai Grand i10 1.2 Kappa Sportz Option": 3,
    "Mercedes-Benz E-Class 2009-2013 E250 CDI Avantgarde": 3,
    "Nissan Micra XL": 3,
    "Maruti 800 AC": 3,
    "Chevrolet Optra Magnum 2.0 LT": 3,
    "Maruti Wagon R LX": 3,
    "Honda City 1.3 EXI": 3,
    "Maruti Dzire LDI": 3,
    "BMW 7 Series 730Ld": 3,
    "Skoda Laura 1.8 TSI Ambiente": 3,
    "Honda Civic 2010-2013 1.8 S MT": 3,
    "Honda Amaze E i-Dtech": 3,
    "Maruti Zen LX": 3,
    "Maruti 800 Std BSIII": 3,
    "Volkswagen Polo 1.5 TDI Comfortline": 3,
    "Hyundai Verna 1.6 CRDi S": 3,
    "Chevrolet Sail 1.2 LS": 3,
    "Hyundai Elite i20 Petrol Sportz": 3,
    "Mercedes-Benz E-Class 200 Kompressor Elegance": 3,
    "Toyota Innova Crysta 2.8 GX AT 8S": 3,
    "Maruti Ritz ZDi": 3,
    "BMW 6 Series Gran Coupe": 3,
    "Maruti Vitara Brezza LDi": 3,
    "Tata Zest Revotron 1.2 XT": 3,
    "Mercedes-Benz M-Class ML 350 CDI": 3,
    "Maruti SX4 Green Vxi (CNG)": 3,
    "Mini Cooper 3 DOOR D": 3,
    "Tata Tiago 1.2 Revotron XZ": 3,
    "Toyota Innova Crysta 2.4 VX MT 8S": 3,
    "Maruti Ciaz 1.3 Alpha": 3,
    "Audi Q7 3.0 TDI quattro": 3,
    "BMW 5 Series 525d Sedan": 3,
    "Maruti Zen Estilo LXI BS IV": 3,
    "Honda Amaze S Petrol": 3,
    "Skoda Rapid 1.5 TDI Ambition": 3,
    "Land Rover Range Rover 2.2L Prestige": 3,
    "Maruti Alto LX": 3,
    "Maruti SX4 ZDI": 3,
    "Mercedes-Benz New C-Class C 220 CDI CLASSIC": 3,
    "Hyundai Xcent 1.2 Kappa SX": 3,
    "Maruti Vitara Brezza VDi": 3,
    "Ford EcoSport 1.5 Petrol Titanium Plus AT": 3,
    "Honda City i DTec V": 3,
    "Mercedes-Benz M-Class ML 320 CDI": 3,
    "Maruti Ciaz VDI SHVS": 3,
    "Honda Jazz VX": 3,
    "Hyundai i10 Magna 1.2 iTech SE": 3,
    "Hyundai Santa Fe 2WD AT": 3,
    "Tata Indica DLS": 3,
    "Maruti Baleno Alpha 1.2": 3,
    "Mercedes-Benz New C-Class C 250 CDI Avantgarde": 3,
    "Mercedes-Benz C-Class Progressive C 220d": 3,
    "BMW 3 Series 2005-2011 325i Sedan": 3,
    "Hyundai Getz GLS": 3,
    "Mitsubishi Pajero Sport 4X4 AT": 3,
    "Skoda Octavia Classic 1.9 TDI MT": 3,
    "Mercedes-Benz E-Class E250 CDI Launch Edition": 3,
    "Honda Jazz 1.2 V i VTEC": 3,
    "BMW X5 xDrive 30d M Sport": 3,
    "Skoda Superb 1.8 TSI MT": 3,
    "Mini Cooper S Carbon Edition": 3,
    "Hyundai Creta 1.4 E Plus Diesel": 3,
    "Land Rover Range Rover 2.2L Dynamic": 3,
    "Hyundai Xcent 1.2 Kappa AT SX Option": 3,
    "Honda CR-V 2.4L 4WD AT": 3,
    "Nissan Terrano XL D Option": 3,
    "BMW 3 Series 320d Corporate Edition": 3,
    "Nissan Terrano XL 110 PS": 3,
    "Audi Q3 2012-2015 35 TDI Quattro Premium Plus": 3,
    "Ford Figo 2015-2019 1.2P Titanium MT": 3,
    "Mercedes-Benz S Class 2005 2013 S 350 L": 3,
    "Honda Accord 2.4 Inspire M/T": 3,
    "Mercedes-Benz M-Class ML 350 CDI Corporate": 3,
    "Honda Jazz 1.5 S i DTEC": 3,
    "Skoda Laura 1.9 TDI AT Ambiente": 3,
    "Maruti S Cross DDiS 320 Alpha": 3,
    "Mahindra Ssangyong Rexton RX5": 3,
    "Honda Amaze S i-VTEC": 3,
    "Honda City i DTEC VX Option": 3,
    "Maruti Zen Estilo LXI BSIII": 3,
    "Honda CR-V 2.4 4WD AT": 3,
    "Mercedes-Benz R-Class R350 4Matic Long": 3,
    "Mercedes-Benz New C-Class C 250 CDI Elegance": 3,
    "Maruti Swift Dzire LDi": 3,
    "Volkswagen Polo 1.2 MPI Trendline": 3,
    "Toyota Corolla Altis VL AT": 3,
    "Maruti Omni 8 Seater BSII": 3,
    "Mercedes-Benz GLC 220d 4MATIC Style": 3,
    "Honda Amaze S Diesel": 3,
    "Maruti Swift DDiS VDI": 3,
    "Mercedes-Benz E-Class 2009-2013 E 250 Elegance": 3,
    "Skoda Octavia Elegance 1.8 TSI AT": 3,
    "Ford EcoSport 1.0 Ecoboost Titanium Plus": 3,
    "Ford Ikon 1.4 TDCi DuraTorq": 3,
    "Honda CR-V 2.4 MT": 3,
    "BMW 3 Series 320d Sport": 3,
    "Ford EcoSport 1.5 Ti VCT MT Titanium BE": 3,
    "Fiat Linea Emotion": 3,
    "Volkswagen Jetta 2007-2011 1.9 Highline TDI": 3,
    "Ford Fiesta 1.4 Duratorq ZXI": 3,
    "Hyundai Verna VTVT 1.6 SX Option": 3,
    "Tata Sumo EX": 3,
    "Audi A4 35 TDI Premium Plus": 3,
    "Maruti Ciaz Zeta": 3,
    "Mercedes-Benz New C-Class 220 CDI MT": 3,
    "Renault Koleos 2.0 Diesel": 3,
    "Tata Indigo LX": 3,
    "Audi A6 2.0 TDI Design Edition": 3,
    "Maruti SX4 VDI": 2,
    "Mini Cooper Countryman D": 2,
    "Maruti Swift Dzire 1.2 Lxi BSIV": 2,
    "Nissan X-Trail SLX MT": 2,
    "Toyota Corolla Altis 1.8 G": 2,
    "Skoda Octavia Ambiente 1.9 TDI MT": 2,
    "Maruti Omni MPI STD BSIV": 2,
    "Mahindra Xylo E4 ABS BS III": 2,
    "Mahindra Scorpio S6 7 Seater": 2,
    "Mahindra Scorpio VLX 2WD BSIV": 2,
    "Audi A4 35 TDI Technology Edition": 2,
    "Honda Jazz V CVT": 2,
    "Mercedes-Benz New C-Class 200 Kompressor": 2,
    "Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV": 2,
    "Hyundai Verna 1.6 VTVT EX AT": 2,
    "Toyota Innova 2.5 GX 7 STR": 2,
    "Audi A4 2.0 TDI Premium Sport Limited Edition": 2,
    "Honda Amaze VX AT i-Vtech": 2,
    "Ford EcoSport 1.5 Diesel Titanium Plus": 2,
    "Tata Manza Club Class Quadrajet90 LS": 2,
    "Toyota Innova 2.0 GX 8 STR": 2,
    "Skoda Laura Ambition 2.0 TDI CR AT": 2,
    "Honda CR-V RVi MT": 2,
    "Volkswagen Jetta 2007-2011 2.0 TDI Comfortline": 2,
    "Mercedes-Benz GLA Class 200 d Sport": 2,
    "Chevrolet Optra Magnum 1.6 LT ABS BS3": 2,
    "Land Rover Range Rover Sport SE": 2,
    "Maruti Baleno RS Petrol": 2,
    "Volkswagen Jetta 2007-2011 2.0 TDI Trendline": 2,
    "Hyundai i10 Asta Sunroof AT": 2,
    "Renault KWID AMT RXL": 2,
    "Maruti Swift Dzire VXi AT": 2,
    "Mercedes-Benz New C-Class C 200 CGI Elegance": 2,
    "Hyundai Creta 1.6 SX Automatic Diesel": 2,
    "Mini Cooper Countryman D High": 2,
    "Hyundai Santro Xing XG eRLX Euro III": 2,
    "BMW 5 Series 2010-2013 525i": 2,
    "BMW X6 xDrive 40d M Sport": 2,
    "Ford EcoSport 1.5 Petrol Titanium": 2,
    "Mercedes-Benz E-Class E270 CDI": 2,
    "Skoda Rapid 1.6 MPI Elegance": 2,
    "Hyundai i20 Active 1.4 SX Dual Tone": 2,
    "Renault Duster 110PS Diesel RxL AMT": 2,
    "Maruti Celerio ZXI MT": 2,
    "Hyundai Verna 1.6 CRDi AT SX": 2,
    "Audi A4 3.0 TDI Quattro Premium": 2,
    "Mini Cooper 3 DOOR S": 2,
    "Tata Tiago 1.2 Revotron XT": 2,
    "Toyota Etios Cross 1.4L VD": 2,
    "Mercedes-Benz E-Class 230 E AT": 2,
    "Honda City i-DTEC ZX": 2,
    "Hyundai Santro Xing GLS LPG": 2,
    "Toyota Corolla Altis D-4D GL": 2,
    "Nissan Sunny 2011-2014 XV": 2,
    "Honda CR-V 2.0 AT": 2,
    "Tata Tiago AMT 1.2 Revotron XZA": 2,
    "Hyundai i20 Asta Optional with Sunroof 1.2": 2,
    "Maruti SX4 Zxi BSIII": 2,
    "Toyota Etios Liva V": 2,
    "Hyundai Xcent 1.2 Kappa S Option CNG": 2,
    "BMW 5 Series 520d Sport Line": 2,
    "Skoda Rapid 1.6 MPI AT Elegance": 2,
    "Maruti Ciaz Alpha": 2,
    "Tata Safari DICOR 2.2 LX 4x2": 2,
    "Honda Jazz Select Edition": 2,
    "Ford Figo 2015-2019 1.2P Titanium Opt MT": 2,
    "Volkswagen Polo GTI": 2,
    "Honda City i VTEC CVT SV": 2,
    "Honda Jazz 1.5 V i DTEC": 2,
    "Maruti Grand Vitara 2.4 MT": 2,
    "Tata Indica V2 eLX": 2,
    "Hyundai Verna CRDi 1.6 SX": 2,
    "Ford Endeavour 2.2 Trend MT 4X4": 2,
    "Mahindra XUV500 W8 1.99 mHawk": 2,
    "Toyota Etios Cross 1.4 GD": 2,
    "Mahindra Thar CRDe AC": 2,
    "Skoda Laura Elegance 2.0 TDI CR AT": 2,
    "Audi A7 2011-2015 3.0 TDI Quattro": 2,
    "Ford Ecosport 1.0 Ecoboost Platinum Edition": 2,
    "BMW 5 Series 523i Sedan": 2,
    "Hyundai i20 Active 1.4 SX": 2,
    "Honda Jazz 1.2 S i VTEC": 2,
    "Tata Zest Quadrajet 1.3 XT": 2,
    "Ford Endeavour 2.2 Titanium AT 4X2": 2,
    "Volkswagen Vento Sport 1.2 TSI AT": 2,
    "BMW 3 Series 320d GT Luxury Line": 2,
    "Mahindra Scorpio 2.6 CRDe": 2,
    "Honda City i-VTEC CVT ZX": 2,
    "Honda Amaze V CVT Petrol": 2,
    "Ford Endeavour 4x2 XLT Limited Edition": 2,
    "Audi Q3 2012-2015 35 TDI Quattro Premium": 2,
    "Fiat Punto EVO 1.2 Emotion": 2,
    "Honda City 1.5 V AT Exclusive": 2,
    "Mahindra Xylo E8 ABS BS IV": 2,
    "Honda City V MT AVN": 2,
    "Mercedes-Benz E-Class 220 CDI": 2,
    "Renault Duster 110PS Diesel RXZ Option": 2,
    "Hyundai i20 Sportz Option Diesel": 2,
    "Audi A4 2.0 TDI 177 Bhp Technology Edition": 2,
    "Hyundai Verna 1.4 VTVT": 2,
    "Mahindra TUV 300 T8": 2,
    "Mercedes-Benz S-Class 280 AT": 2,
    "Ford Figo Petrol EXI": 2,
    "Hyundai i20 1.4 Asta CRDi with AVN": 2,
    "Maruti Vitara Brezza ZDi Plus AMT Dual Tone": 2,
    "Mercedes-Benz S-Class 320 L": 2,
    "Maruti Baleno Delta Automatic": 2,
    "Honda Mobilio V i DTEC": 2,
    "Tata Nano Lx": 2,
    "Hyundai Xcent 1.2 Kappa AT S Option": 2,
    "Maruti Zen Estilo 1.1 VXI BSIII": 2,
    "Porsche Cayenne Diesel": 2,
    "Renault KWID Climber 1.0 MT": 2,
    "Mahindra Verito 1.5 D6 BSIV": 2,
    "Hyundai Verna 1.6 CRDi EX MT": 2,
    "Maruti Zen Estilo 1.1 LX BSIII": 2,
    "Honda City i-DTEC SV": 2,
    "Hyundai Xcent 1.2 CRDi E Plus": 2,
    "Toyota Etios VXD": 2,
    "Mahindra Scorpio VLX 2WD AIRBAG BSIV": 2,
    "Mahindra Xylo E4": 2,
    "Skoda Superb 2.8 V6 AT": 2,
    "Volkswagen Polo 1.2 MPI Highline Plus": 2,
    "Toyota Innova 2.5 G3": 2,
    "Mercedes-Benz CLA 200 Sport Edition": 2,
    "Mercedes-Benz GLA Class 200 Sport Edition": 2,
    "Ford Fiesta 1.4 SXi TDCi ABS": 2,
    "Toyota Etios G Safety": 2,
    "Maruti Swift 1.3 LXI": 2,
    "Chevrolet Aveo 1.4 LS": 2,
    "Maruti Ritz ZXi": 2,
    "Audi A4 3.0 TDI Quattro": 2,
    "Hyundai Grand i10 1.2 CRDi Sportz Option": 2,
    "Hyundai Grand i10 CRDi Asta": 2,
    "Tata Indigo CS Emax CNG GLX": 2,
    "Hyundai Elite i20 Asta Option": 2,
    "Tata Manza ELAN Quadrajet BS IV": 2,
    "Land Rover Discovery Sport TD4 HSE 7S": 2,
    "BMW 7 Series 740Li": 2,
    "Toyota Innova 2.5 GX (Diesel) 7 Seater BS IV": 2,
    "Hyundai Verna 1.6 CRDI AT SX Option": 2,
    "BMW X3 xDrive30d M Sport": 2,
    "Tata Indica Vista Aqua 1.3 Quadrajet": 2,
    "Skoda Octavia 2.0 TDI AT Style Plus": 2,
    "Ford Endeavour 2.5L 4X2": 2,
    "Maruti Baleno Delta": 2,
    "Ford Aspire Titanium Diesel": 2,
    "Mahindra Thar CRDe": 2,
    "Volvo V40 Cross Country D3": 2,
    "Hyundai Santro Xing XG": 2,
    "Maruti Zen VXI BSII": 2,
    "Volkswagen Jetta 2012-2014 2.0L TDI Comfortline": 2,
    "Skoda Yeti Elegance": 2,
    "Maruti Zen LXI": 2,
    "Jaguar XJ 3.0L Portfolio": 2,
    "Tata Zest Revotron 1.2T XMS": 2,
    "Tata Indica Vista Aura 1.3 Quadrajet": 2,
    "Tata Bolt Quadrajet XE": 2,
    "Maruti Zen Estilo LXI Green (CNG)": 2,
    "Maruti Alto Std": 2,
    "Honda Brio S Option AT": 2,
    "Maruti Ciaz ZXi Option": 2,
    "Hyundai i20 Sportz Petrol": 2,
    "Hyundai Verna Transform SX VGT CRDi": 2,
    "Chevrolet Enjoy 1.3 TCDi LTZ 8": 2,
    "Maruti Ciaz 1.4 Zeta": 2,
    "Tata Hexa XTA": 2,
    "Tata Nano XT": 2,
    "Honda Accord 2001-2003 2.3 VTi L AT": 2,
    "Mahindra Quanto C8": 2,
    "Toyota Corolla H5": 2,
    "Maruti Celerio LXI": 2,
    "Hyundai Verna CRDi ABS": 2,
    "Skoda Superb Style 2.0 TDI AT": 2,
    "Ford Fiesta Classic 1.4 Duratorq LXI": 2,
    "Maruti 800 Std": 2,
    "Force One LX 4x4": 2,
    "Hyundai Santro GLS I - Euro I": 2,
    "Mercedes-Benz New C-Class C 200 Avantgarde Edition C": 2,
    "Maruti Ciaz 1.4 Delta": 2,
    "Mahindra NuvoSport N6": 2,
    "Skoda Fabia 1.2 MPI Ambiente Petrol": 2,
    "Mitsubishi Outlander 2.4": 2,
    "Tata Nexon 1.5 Revotorq XZ Plus Dual Tone": 2,
    "Tata Indigo eCS eLX BS IV": 2,
    "Ford Fiesta 1.4 Duratec ZXI": 2,
    "Mahindra Xylo D4 BS III": 2,
    "Audi Q5 30 TDI quattro Premium": 2,
    "Toyota Innova 2.5 Z Diesel 7 Seater": 2,
    "Hyundai EON D Lite": 2,
    "Ford Freestyle Titanium Plus Petrol": 2,
    "Renault Fluence Diesel E4": 2,
    "BMW X5 X5 M": 2,
    "Mitsubishi Cedia Sports": 2,
    "Mercedes-Benz CLA 200 D Sport Edition": 2,
    "Mercedes-Benz New C-Class C 200 CGI": 2,
    "Renault KWID 1.0 RXT Optional AMT": 2,
    "BMW X3 xDrive 20d Luxury Line": 2,
    "Maruti Wagon R Stingray VXI": 2,
    "Ford Endeavour 2.5L 4X2 MT": 2,
    "Maruti Swift DDiS ZDI Plus": 2,
    "Maruti Ertiga SHVS ZDI Plus": 2,
    "Mahindra Scorpio 2009-2014 SLE 7S BSIV": 2,
    "Datsun GO NXT": 2,
    "Hyundai i20 Asta (o) 1.4 CRDi (Diesel)": 2,
    "Hyundai EON D Lite Plus Option": 2,
    "Honda Accord 2.4 Elegance M/T": 2,
    "Maruti Ignis 1.2 Alpha": 2,
    "Renault Duster 85PS Diesel RxL Explore": 2,
    "Toyota Innova Crysta 2.4 GX MT": 2,
    "Ford Ecosport Signature Edition Diesel": 2,
    "Toyota Etios VD": 2,
    "Maruti Wagon R LX BSII": 2,
    "Maruti Baleno Alpha Automatic": 2,
    "Audi RS5 Coupe": 2,
    "Mercedes-Benz A Class A180 Sport": 2,
    "Hyundai Verna 1.6 EX VTVT": 2,
    "Maruti Swift VDI Optional": 2,
    "Land Rover Range Rover Evoque 2.0 TD4 HSE Dynamic": 2,
    "Chevrolet Beat Diesel PS": 2,
    "Ford Endeavour 2.2 Trend AT 4X2": 2,
    "Audi Q5 2008-2012 2.0 TFSI Quattro": 2,
    "Ford Figo 1.5D Trend MT": 2,
    "Toyota Etios V": 2,
    "Audi Q3 30 TDI Premium FWD": 2,
    "Hyundai Xcent 1.2 Kappa Base": 2,
    "Maruti Ciaz VDi Plus": 2,
    "Skoda Fabia 1.2 MPI Classic": 2,
    "Hyundai Creta 1.4 CRDi S Plus": 2,
    "Maruti Wagon R LXI BSII": 2,
    "Mercedes-Benz E-Class Facelift": 2,
    "Volkswagen Vento IPL II Petrol Highline AT": 2,
    "Honda Mobilio RS i DTEC": 2,
    "Maruti Baleno Zeta 1.3": 2,
    "Chevrolet Aveo 1.4": 2,
    "Toyota Innova Crysta 2.4 GX MT 8S": 2,
    "Tata Nano Lx BSIV": 2,
    "Nissan Terrano XV D Pre": 2,
    "Land Rover Range Rover 3.0 D": 2,
    "Tata Indica V2 DLS": 2,
    "Skoda Yeti Ambition 4X2": 2,
    "Renault KWID Climber 1.0 AMT": 2,
    "Hyundai Accent GLS": 2,
    "Nissan Terrano XL Plus 85 PS": 2,
    "Mahindra Scorpio 2.6 SLX CRDe": 2,
    "Ford Figo 2015-2019 1.5D Titanium MT": 2,
    "Honda CR-V 2.0L 2WD AT": 2,
    "Jeep Compass 2.0 Limited Option 4X4": 2,
    "BMW 3 Series 330d Convertible": 2,
    "Honda City 1.5 V AT Sunroof": 2,
    "Skoda Laura Ambiente 2.0 TDI CR MT": 2,
    "Skoda Octavia Ambition 1.4 TSI MT": 2,
    "Renault Lodgy 110PS RxZ 8 Seater": 2,
    "Maruti Dzire AMT ZXI Plus": 2,
    "Hyundai Xcent 1.2 Kappa SX Option": 2,
    "Land Rover Range Rover Evoque 2.0 TD4 Pure": 2,
    "Tata Indigo CS eGLX BS IV": 2,
    "Maruti Zen Estilo VXI BSIII": 2,
    "Skoda Rapid 1.6 MPI Ambition With Alloy Wheel": 2,
    "Ford Figo Aspire 1.2 Ti-VCT Trend": 2,
    "Maruti Baleno LXI": 2,
    "Mahindra Scorpio 2.6 DX": 2,
    "Skoda Laura 1.9 TDI MT Ambiente": 2,
    "Toyota Innova 2.5 VX (Diesel) 7 Seater BS IV": 2,
    "Land Rover Discovery Sport TD4 HSE": 2,
    "Hyundai Verna 1.6 CRDi EX AT": 2,
    "Honda City i VTEC S": 2,
    "Maruti Alto Green LXi (CNG)": 2,
    "Volkswagen Vento 1.5 Highline Plus AT 16 Alloy": 2,
    "Chevrolet Enjoy Petrol LS 7 Seater": 2,
    "Maruti Wagon R LXI Optional": 2,
    "Tata Manza Aqua Quadrajet BS IV": 2,
    "Hyundai i10 Magna Optional 1.1L": 2,
    "BMW 3 Series 320d M Sport": 2,
    "Honda Amaze EX i-Dtech": 2,
    "BMW 5 Series 2003-2012 530d Highline": 2,
    "BMW X3 xDrive20d xLine": 2,
    "Maruti Ciaz 1.3 S": 2,
    "Honda City 1.5 V MT Sunroof": 2,
    "Ford Fiesta 1.4 SXi TDCi": 2,
    "Toyota Fortuner 4x4 MT TRD Sportivo": 2,
    "Maruti Vitara Brezza LDi Option": 2,
    "Ford Endeavour XLT TDCi 4X2": 2,
    "Mercedes-Benz SLK-Class SLK 350": 2,
    "Mercedes-Benz GLC 220": 2,
    "Audi A6 35 TFSI Matrix": 2,
    "Mahindra Scorpio 2.6 LX": 2,
    "Land Rover Range Rover Vogue SE 4.4 SDV8": 2,
    "Mahindra Scorpio S8 8 Seater": 2,
    "Fiat Linea Emotion (Diesel)": 2,
    "Tata Xenon XT EX 4X2": 2,
    "Audi A6 2011-2015 35 TFSI Technology": 2,
    "Honda Jazz 1.5 SV i DTEC": 2,
    "Maruti Swift LDI Optional": 2,
    "Mercedes-Benz E-Class 2015-2017 E350 CDI Avantgrade": 2,
    "Volvo S60 D4 Momentum": 2,
    "Maruti Ciaz RS ZDi Plus SHVS": 2,
    "Tata Safari Storme 2012-2015 VX": 2,
    "Hyundai Verna VTVT 1.6 AT SX Option": 2,
    "Honda City i DTEC S": 2,
    "Hyundai Grand i10 CRDi Sportz Celebration Edition": 2,
    "Land Rover Discovery Sport SD4 HSE Luxury 7S": 2,
    "Fiat Linea Emotion Pack (Diesel)": 2,
    "BMW X1 M Sport sDrive 20d": 2,
    "Ford EcoSport 1.5 Ti VCT AT Titanium BE": 2,
    "Volkswagen Vento Petrol Trendline": 2,
    "Hyundai Accent CRDi": 2,
    "Tata Indica GLS BS IV": 2,
    "Audi A4 1.8 TFSI": 2,
    "Jaguar XF 2.2 Litre Executive": 2,
    "Mahindra KUV 100 mFALCON G80 K2": 2,
    "Land Rover Freelander 2 HSE": 2,
    "Ford EcoSport 1.5 TDCi Trend": 2,
    "Maruti Esteem Vxi": 2,
    "Volkswagen Vento 1.5 TDI Comfortline AT": 2,
    "Hyundai Santro GLS I - Euro II": 2,
    "Maruti S Cross DDiS 200 Alpha": 2,
    "Ford Figo Aspire 1.2 Ti-VCT Ambiente": 2,
    "Maruti Alto 800 2016-2019 LXI Optional": 2,
    "Honda Amaze S i-DTEC": 2,
    "Hyundai Xcent 1.2 VTVT S": 2,
    "Nissan Micra Active XV": 2,
    "Chevrolet Enjoy TCDi LS 8 Seater": 2,
    "Jeep Compass 2.0 Sport": 2,
    "Audi Q5 3.0 TDI Quattro": 2,
    "Audi A8 L 3.0 TDI quattro": 2,
    "Jaguar XE 2.0L Diesel Prestige": 2,
    "Maruti Ciaz 1.4 AT Alpha": 2,
    "Chevrolet Sail Hatchback 1.2 LS": 2,
    "Maruti 800 DX BSII": 2,
    "Mahindra Scorpio VLX 2.2 mHawk BSIII": 2,
    "Honda Brio EX MT": 2,
    "Volvo S60 D4 KINETIC": 2,
    "Hyundai i20 Asta Option 1.4 CRDi": 2,
    "Audi Q7 35 TDI Quattro Premium Plus": 2,
    "Skoda Superb 3.6 V6 FSI": 2,
    "Maruti Wagon R VXI BSIII": 2,
    "Volkswagen Polo GT TDI": 2,
    "Maruti SX4 Zxi with Leather BSIII": 2,
    "Honda BR-V i-VTEC S MT": 2,
    "Maruti Esteem Vxi - BSIII": 2,
    "Skoda Rapid 1.6 MPI Ambition": 2,
    "Hyundai i20 Asta 1.4 CRDi (Diesel)": 2,
    "Skoda Rapid 1.6 MPI AT Style": 2,
    "Toyota Corolla Altis GL MT": 2,
    "Ford Figo Aspire 1.2 Ti-VCT Titanium": 2,
    "Ford Fiesta 1.4 Duratec EXI": 2,
    "Maruti Baleno Alpha CVT": 2,
    "Tata Indigo GLE": 2,
    "ISUZU D-MAX V-Cross 4X4": 2,
    "Maruti Ignis 1.2 Delta": 2,
    "Maruti A-Star AT VXI": 2,
    "Audi A4 35 TDI Technology": 2,
    "Ford Fiesta 1.4 ZXi TDCi ABS": 2,
    "Maruti Swift VXI BSIII W/ ABS": 2,
    "Renault Captur 1.5 Diesel Platine Mono": 2,
    "Mitsubishi Pajero 2.8 GLX CRZ": 2,
    "Tata Indigo CS LX (TDI) BS III": 2,
    "BMW 5 Series 530d M Sport": 2,
    "Hyundai Grand i10 SportZ Edition": 2,
    "Hyundai i20 Active 1.2 SX": 2,
    "Toyota Etios VX": 2,
    "Mahindra Thar DI 4X4": 2,
    "Skoda Octavia Ambition 2.0 TDI AT": 2,
    "Mercedes-Benz New C-Class 200 CDI Classic": 2,
    "Mercedes-Benz SLC 43 AMG": 2,
    "Hyundai Verna VTVT 1.6 AT SX Plus": 2,
    "Maruti Celerio CNG VXI MT": 2,
    "Nissan Terrano XL 85 PS": 2,
    "Hyundai Grand i10 CRDi SportZ Edition": 2,
    "Honda City i DTec VX": 2,
    "Hyundai Verna Xi (Petrol)": 2,
    "BMW 1 Series 118d Base": 2,
    "Hyundai Verna 1.4 EX": 2,
    "Maruti Swift VDi BSIII W/ ABS": 2,
    "Maruti Swift VVT VXI": 2,
    "Maruti Swift LXI": 2,
    "Hyundai Tucson CRDi": 2,
    "Chevrolet Aveo U-VA 1.2 LT": 2,
    "Toyota Etios Liva GD SP": 2,
    "Tata Hexa XT": 2,
    "Honda Amaze V Petrol": 2,
    "Ford Fiesta 1.4 TDCi EXI": 2,
    "Audi TT 2.0 TFSI": 2,
    "Mahindra Verito 1.5 D4 BSIV": 2,
    "Mahindra Scorpio S10 4WD": 2,
    "Jeep Compass 2.0 Limited": 2
}
